export const Images = {
  Algebric: require('./algebric.png'),
  Equations: require('./equations.png'),
  Combinations: require('./combinations.png'),
  Sequences: require('./sequences.png'),
  Formula: require('./formula.png'),
  Plainimetry: require('./plainimetry.png'),
  Stereometry: require('./stereometry.png'),
  Logo: require('./Logo.png'),
  DummyDP: require('./dummyDp.png'),
  QuestionMark: require('./questionMark.png'),
  TickMark: require('./tickMark.png'),
  CrossMark: require('./crossMark.png'),
  OpenBookIcon: require('./openBookIcon.png'),
  CategoryIcon: require('./categoryIcon.png'),
  GoogleIcon: require('./googleIcon.png'),
  dpPlaceholder: require('./dpPlaceholder.png'),
};
